In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['flower']=iris.target

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [30]:
df.shape

(150, 5)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   flower             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [31]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
flower               0
dtype: int64

In [10]:
df.flower.value_counts()

2    50
1    50
0    50
Name: flower, dtype: int64

In [11]:
x=df.iloc[:,0:3]
y=df['flower']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=10)

In [14]:
reg=LogisticRegression()
reg.fit(xtrain,ytrain)

LogisticRegression()

In [15]:
reg.coef_

array([[-0.4073167 ,  0.94477968, -2.460912  ],
       [ 0.65300183, -0.64180011, -0.49642862],
       [-0.24568513, -0.30297957,  2.95734063]])

In [16]:
reg.intercept_

array([  8.19927559,   1.97085122, -10.17012681])

In [20]:
ypred=reg.predict(xtest)

In [22]:
pd.DataFrame(ypred,ytest)

0
flower   
1       1
2       2
0       0
1       1
0       0
1       1
1       1
1       1
0       0
1       1
1       1
2       2
1       1
0       0
0       0
2       2
1       1
0       0
0       0
0       0
2       2
2       2
2       1
0       0
1       1
0       0
1       1
1       1
1       1
2       2
1       1
1       1
2       2
2       2
2       2
0       0
2       2
2       2
2       2
2       2
0       0
0       0
1       1
0       0
1       1

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [24]:
confusion_matrix(ytest,ypred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  1, 13]], dtype=int64)

In [25]:
reg.score(xtest,ytest)

0.9777777777777777

In [26]:
reg.score(xtrain,ytrain)

0.9619047619047619

In [29]:
accuracy_score(ytest,ypred)

0.9777777777777777